on: [push, pull_request]
name: Build
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sqlite3 deps
        run: |
          sudo apt-get update
          sudo apt-get install gcc -y

      - name: Build
        run: go build .